// Generated by scripts/gen-schemas.mjs from pi-autoresearch@939ede8 index.ts:196-267
// (RunParams, InitParams, LogParams, evaluated with upstream's TypeBox). Do not edit.

export const TOOL_SCHEMAS: Record<"init_experiment" | "run_experiment" | "log_experiment", Record<string, unknown>> = {
  "init_experiment": {
    "type": "object",
    "required": [
      "name",
      "metric_name"
    ],
    "properties": {
      "name": {
        "description": "Human-readable name for this experiment session (e.g. \"Optimizing liquid for fastest execution and parsing\")",
        "type": "string"
      },
      "metric_name": {
        "description": "Display name for the primary metric (e.g. \"total_µs\", \"bundle_kb\", \"val_bpb\"). Shown in dashboard headers.",
        "type": "string"
      },
      "metric_unit": {
        "description": "Unit for the primary metric. Use \"µs\", \"ms\", \"s\", \"kb\", \"mb\", or \"\" for unitless. Affects number formatting. Default: \"\"",
        "type": "string"
      },
      "direction": {
        "description": "Whether \"lower\" or \"higher\" is better for the primary metric. Default: \"lower\".",
        "type": "string"
      }
    }
  },
  "run_experiment": {
    "type": "object",
    "required": [
      "command"
    ],
    "properties": {
      "command": {
        "description": "Shell command to run (e.g. 'pnpm test:vitest', 'uv run train.py')",
        "type": "string"
      },
      "timeout_seconds": {
        "description": "Kill after this many seconds (default: 600)",
        "type": "number"
      },
      "checks_timeout_seconds": {
        "description": "Kill .auto/checks.sh after this many seconds (default: 300). Only relevant when the checks file exists.",
        "type": "number"
      }
    }
  },
  "log_experiment": {
    "type": "object",
    "required": [
      "commit",
      "metric",
      "status",
      "description"
    ],
    "properties": {
      "commit": {
        "description": "Git commit hash (short, 7 chars)",
        "type": "string"
      },
      "metric": {
        "description": "The primary optimization metric value (e.g. seconds, val_bpb). 0 for crashes.",
        "type": "number"
      },
      "status": {
        "type": "string",
        "enum": [
          "keep",
          "discard",
          "crash",
          "checks_failed"
        ]
      },
      "description": {
        "description": "Short description of what this experiment tried",
        "type": "string"
      },
      "metrics": {
        "additionalProperties": {
          "type": "number"
        },
        "description": "Additional metrics to track as { name: value } pairs, e.g. { \"compile_µs\": 4200, \"render_µs\": 9800 }. These are shown alongside the primary metric for tradeoff monitoring.",
        "type": "object",
        "properties": {}
      },
      "force": {
        "description": "Set to true to allow adding a new secondary metric that wasn't tracked before. Only use for metrics that have proven very valuable to watch.",
        "type": "boolean"
      },
      "asi": {
        "additionalProperties": {},
        "description": "Actionable Side Information — structured diagnostics for this run. Free-form key/value pairs. Parsed ASI from run_experiment output is merged automatically; use this to add or override fields.",
        "type": "object",
        "properties": {}
      }
    }
  }
};
