// Generates plugin/hooks/upstream/schemas.ts from upstream's own TypeBox tool
// parameter definitions (upstream/extensions/pi-autoresearch/index.ts), evaluated with
// upstream's installed TypeBox and pi-ai StringEnum (run `npm ci` in upstream/ first).
//
//   node scripts/gen-schemas.mjs
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const upstream = join(root, "upstream");
const source = readFileSync(join(upstream, "extensions/pi-autoresearch/index.ts"), "utf8");

const start = source.indexOf("const RunParams = Type.Object(");
const endMarker = "// Helpers";
const end = source.indexOf(endMarker, start);
if (start < 0 || end < 0) throw new Error("tool schema block not found in upstream index.ts");
const block = source.slice(start, end).replace(/^\/\/ -+\s*$/gm, "").replace("export const LogParams", "const LogParams");

const dir = mkdtempSync(join(upstream, ".gen-schemas-"));
try {
  const file = join(dir, "schemas.mts");
  writeFileSync(file, [
    'import { Type } from "@sinclair/typebox";',
    'import { StringEnum } from "@earendil-works/pi-ai";',
    block,
    "export { RunParams, InitParams, LogParams };",
  ].join("\n"));
  const mod = await import(pathToFileURL(file).href);
  const plain = (schema) => JSON.parse(JSON.stringify(schema));
  const out = {
    init_experiment: plain(mod.InitParams),
    run_experiment: plain(mod.RunParams),
    log_experiment: plain(mod.LogParams),
  };
  const target = join(root, "plugin/hooks/upstream/schemas.ts");
  writeFileSync(target, [
    "// Generated by scripts/gen-schemas.mjs from pi-autoresearch@939ede8 index.ts:196-267",
    "// (RunParams, InitParams, LogParams, evaluated with upstream's TypeBox). Do not edit.",
    "",
    `export const TOOL_SCHEMAS: Record<"init_experiment" | "run_experiment" | "log_experiment", Record<string, unknown>> = ${JSON.stringify(out, null, 2)};`,
    "",
  ].join("\n"));
  console.log(`wrote ${target}`);
} finally {
  rmSync(dir, { recursive: true, force: true });
}
